
# workflow 이름
name: CD with Gradle

# workflow가 언제 실행될 건지 정
on:
  push:
    paths:
      - "Backend/*"
    branches: [ "main" ]
  pull_request: 
    paths:
      - "Backend/*"
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Github Repository
    - uses: actions/checkout@v3

    - name: Set up JDK 17   # JDK 설
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    # 깃허브 시크릿에서 값을 읽어 application.yml 생성
    - name: make application.yml
      env:
        APPLICATION_YML: ${{ secrets.APPLICATION_YML}}
        APPLICATION_YML_DIR: ./Backend/src/main/resources
        APPLICATION_YML_NAME: application.yml
      run: echo $APPLICATION_YML | base64 --decode > $APPLICATION_YML_DIR/$APPLICATION_YML_NAME
      shell: bash
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: ./Backend
        
    - name: Docker build & push to docker repo
     run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/ssoc   .
          docker push ${{ secrets.DOCKER_REPO }}/ssoc
        
    - name: Deploy to server
         uses: appleboy/ssh-action@master
         id: deploy
         with:
           host: ${{ secrets.HOST }}
           username: ubuntu
           key: ${{ secrets.KEY }}
           envs: GITHUB_SHA
         script: |
           sudo docker rm -f $(docker ps -qa)
           sudo docker pull ${{ secrets.DOCKER_REPO }}/ssoc
           docker-compose up -d
           docker image prune -f
